### PR TITLE
feat: memeory size and timeout config for lambda

### PR DESCRIPTION
**Pull request by xiaohanxu-nick**
# Feature
Implements part of #10

Fixes #

### CODE REVIEW

**Comment by ematipico** [comment]
Hi @Xiaohanxu1996 , thank you for your contribution! I run the CI and it failed! The new properties are missing from the `.d.ts` files apparently

**Comment by xiaohanxu-nick** [comment]
> Hi @Xiaohanxu1996 , thank you for your contribution! I run the CI and it failed! The new properties are missing from the `.d.ts` files apparently

ok, working on it.

**Comment by xiaohanxu-nick** [comment]
PR updated

**Comment by ematipico** [comment]
Thank you!

**Pull request merged**
